"""Generates the forge hood and the gas pipe: models and multipart blockstates.

A hood is a brick plate with a skirt round the sides that are not joined to another hood, corner
posts where two skirts would meet, and on top either a collar into whatever the flue goes on into or,
standing alone, a short stub. Side by side, hoods therefore read as one canopy. The pieces never
share a face, so nothing flickers where they meet.

A gas pipe is a copper core with an arm toward every side it is joined on.

Run from the repository root:  python tools/flue_models.py
"""
import json
from pathlib import Path

ASSETS = Path(__file__).resolve().parent.parent / "src/main/resources/assets/hardwrought"
FACES = ("north", "south", "west", "east", "up", "down")


def uv(face, lo, hi):
    x0, y0, z0 = lo
    x1, y1, z1 = hi
    return {
        "north": [16 - x1, 16 - y1, 16 - x0, 16 - y0], "south": [x0, 16 - y1, x1, 16 - y0],
        "west": [z0, 16 - y1, z1, 16 - y0], "east": [16 - z1, 16 - y1, 16 - z0, 16 - y0],
        "up": [x0, z0, x1, z1], "down": [x0, 16 - z1, x1, 16 - z0],
    }[face]


def box(lo, hi, faces=FACES, texture="#brick", special=None):
    special = special or {}
    return {"from": list(lo), "to": list(hi),
            "faces": {f: {"uv": uv(f, lo, hi), "texture": special.get(f, texture)} for f in faces}}


def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


HOOD_TEXTURES = {"brick": "hardwrought:block/hardwrought/forge_brick",
                 "soot": "hardwrought:block/hardwrought/soot",
                 "particle": "hardwrought:block/hardwrought/forge_brick"}
PLATE = box((0, 6, 0), (16, 8, 16), special={"down": "#soot"})
SKIRTS = {
    "north": box((2, 0, 0), (14, 6, 2), ("north", "south", "down")),
    "south": box((2, 0, 14), (14, 6, 16), ("north", "south", "down")),
    "west": box((0, 0, 2), (2, 6, 14), ("west", "east", "down")),
    "east": box((14, 0, 2), (16, 6, 14), ("west", "east", "down")),
}
CORNERS = {
    ("north", "west"): box((0, 0, 0), (2, 6, 2), ("north", "west", "south", "east", "down")),
    ("north", "east"): box((14, 0, 0), (16, 6, 2), ("north", "east", "south", "west", "down")),
    ("south", "west"): box((0, 0, 14), (2, 6, 16), ("south", "west", "north", "east", "down")),
    ("south", "east"): box((14, 0, 14), (16, 6, 16), ("south", "east", "north", "west", "down")),
}
COLLAR = box((4, 8, 4), (12, 16, 12), ("north", "south", "west", "east"))
STUB = box((5, 8, 5), (11, 11, 11), ("north", "south", "west", "east", "up"), special={"up": "#soot"})


def hood():
    models = ASSETS / "models/block/forge_hood"

    def part(name, elements):
        write(models / f"{name}.json", {"parent": "minecraft:block/block",
                                         "__comment": "Generated by tools/flue_models.py.",
                                         "textures": HOOD_TEXTURES, "elements": elements})
        return f"hardwrought:block/forge_hood/{name}"

    multipart = [{"apply": {"model": part("plate", [PLATE])}}]
    for side, element in SKIRTS.items():
        multipart.append({"when": {side: "false"}, "apply": {"model": part(f"skirt_{side}", [element])}})
    for (a, b), element in CORNERS.items():
        multipart.append({"when": {"OR": [{a: "false"}, {b: "false"}]},
                          "apply": {"model": part(f"corner_{a}_{b}", [element])}})
    multipart.append({"when": {"up": "true"}, "apply": {"model": part("collar", [COLLAR])}})
    multipart.append({"when": {"up": "false", "north": "false", "east": "false", "south": "false",
                               "west": "false"}, "apply": {"model": part("stub", [STUB])}})
    write(ASSETS / "blockstates/forge_hood.json", {"multipart": multipart})

    # The item is a hood standing alone.
    write(ASSETS / "models/block/forge_hood.json", {
        "parent": "minecraft:block/block", "__comment": "Generated by tools/flue_models.py: a hood on its own.",
        "textures": HOOD_TEXTURES,
        "elements": [PLATE, *SKIRTS.values(), *CORNERS.values(), STUB]})
    write(ASSETS / "items/forge_hood.json", {"model": {"type": "minecraft:model", "model": "hardwrought:block/forge_hood"}})


PIPE_TEXTURES = {"copper": "hardwrought:block/hardwrought/copper_pipe",
                 "particle": "hardwrought:block/hardwrought/copper_pipe",
                 "soot": "hardwrought:block/hardwrought/soot"}
ARMS = {
    "north": ((5, 5, 0), (11, 11, 5), ("north", "west", "east", "up", "down")),
    "south": ((5, 5, 11), (11, 11, 16), ("south", "west", "east", "up", "down")),
    "west": ((0, 5, 5), (5, 11, 11), ("west", "north", "south", "up", "down")),
    "east": ((11, 5, 5), (16, 11, 11), ("east", "north", "south", "up", "down")),
    "up": ((5, 11, 5), (11, 16, 11), ("up", "north", "south", "west", "east")),
    "down": ((5, 0, 5), (11, 5, 11), ("down", "north", "south", "west", "east")),
}


def pipe():
    models = ASSETS / "models/block/gas_pipe"

    def part(name, elements):
        write(models / f"{name}.json", {"parent": "minecraft:block/block",
                                         "__comment": "Generated by tools/flue_models.py.",
                                         "textures": PIPE_TEXTURES, "elements": elements})
        return f"hardwrought:block/gas_pipe/{name}"

    core = box((5, 5, 5), (11, 11, 11), texture="#copper")
    multipart = [{"apply": {"model": part("core", [core])}}]
    for side, (lo, hi, faces) in ARMS.items():
        # The end of an arm is the joint into the next pipe: its face is never seen, so it is left off.
        faces = tuple(f for f in faces if f != side)
        multipart.append({"when": {side: "true"},
                          "apply": {"model": part(f"arm_{side}", [box(lo, hi, faces, texture="#copper")])}})
    write(ASSETS / "blockstates/gas_pipe.json", {"multipart": multipart})
    write(ASSETS / "items/gas_pipe.json", {"model": {"type": "minecraft:model",
                                                     "model": "hardwrought:block/gas_pipe/item"}})
    write(models / "item.json", {"parent": "minecraft:block/block", "__comment": "Generated by tools/flue_models.py.",
                                 "textures": PIPE_TEXTURES,
                                 "elements": [box((5, 5, 0), (11, 11, 16), texture="#copper",
                                                  special={"north": "#soot", "south": "#soot"})]})


if __name__ == "__main__":
    hood()
    pipe()
    print("hood and pipe written")
