"""Generates the look of the gas block: a faint haze for carbon dioxide, nothing for the rest.

Carbon dioxide, fresh or decayed, gets a pale blue-grey veil that thickens with the units in the
block, so a pool of it in a cave floor, or the layer under the clouds, can just be made out. Methane
and carbon monoxide are invisible, as they are in life: only a safety lamp finds them. The chunk renderer draws the block translucent on its own, because its
texture is partly transparent.

Run from the repository root:  python tools/gas_textures.py
"""
import json
import random
from pathlib import Path

from PIL import Image

ASSETS = Path(__file__).resolve().parent.parent / "src/main/resources/assets/hardwrought"
CAPACITY = 8
HAZE = (196, 206, 214)


def haze(level):
    rng = random.Random(level)
    image = Image.new("RGBA", (16, 16))
    base = 8 + 6 * level                      # 14 .. 56 of 255: a veil, never a wall
    for y in range(16):
        for x in range(16):
            alpha = max(1, base + rng.randint(-4, 4))
            shade = rng.randint(-6, 6)
            image.putpixel((x, y), tuple(c + shade for c in HAZE) + (alpha,))
    return image


def main():
    textures = ASSETS / "textures/block/gas"
    models = ASSETS / "models/block/gas"
    textures.mkdir(parents=True, exist_ok=True)
    models.mkdir(parents=True, exist_ok=True)

    (models / "clear.json").write_text(json.dumps({
        "__comment": "Generated by tools/gas_textures.py: gas nobody can see.",
        "textures": {"particle": "hardwrought:block/gas/haze_1"},
        "elements": [],
    }, indent=2) + "\n", encoding="utf-8")
    for level in range(1, CAPACITY + 1):
        haze(level).save(textures / f"haze_{level}.png")
        faces = {face: {"uv": [0, 0, 16, 16], "texture": "#haze", "cullface": face}
                 for face in ("north", "south", "east", "west", "up", "down")}
        (models / f"haze_{level}.json").write_text(json.dumps({
            "__comment": f"Generated by tools/gas_textures.py: {level} units of carbon dioxide.",
            "textures": {"haze": f"hardwrought:block/gas/haze_{level}",
                         "particle": f"hardwrought:block/gas/haze_{level}"},
            "elements": [{"from": [0, 0, 0], "to": [16, 16, 16], "shade": False, "faces": faces}],
        }, indent=2) + "\n", encoding="utf-8")

    # Carbon dioxide shows by how much of it there is; the decayed kind, which is what gathers under
    # the clouds, shows the same way where there is no fresh carbon dioxide in the block.
    multipart = [{"apply": {"model": "hardwrought:block/gas/clear"}}]
    for level in range(1, CAPACITY + 1):
        multipart.append({"when": {"carbon_dioxide": str(level)},
                          "apply": {"model": f"hardwrought:block/gas/haze_{level}"}})
        multipart.append({"when": {"carbon_dioxide": "0", "decayed_carbon_dioxide": str(level)},
                          "apply": {"model": f"hardwrought:block/gas/haze_{level}"}})
    (ASSETS / "blockstates/gas.json").write_text(json.dumps({"multipart": multipart}, indent=2) + "\n",
                                                 encoding="utf-8")
    print(f"{CAPACITY} haze levels written")


if __name__ == "__main__":
    main()
