"""Generates the wooden and iron hammer from the stone one, and the cracked looks of the wooden anvil.

The hammers keep the stone hammer's shape, handle and binding; only the head is recoloured. The
wooden anvil's cracks are drawn into its vanilla log textures, two stages: cracked and split.
It also writes the anvil's blockstate, which picks the look from how worn it is.

Run from the repository root:  python tools/hammer_and_anvil_textures.py
"""
import json
import zipfile
from io import BytesIO
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "src/main/resources/assets/hardwrought"
JAR = Path.home() / ".gradle/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-clientonly-deobf/26.3/minecraft-clientonly-deobf-26.3.jar"

# The stone head's four tones: highlight, mid, dark (the outline stays).
STONE = {(195, 195, 195): "light", (147, 146, 146): "mid", (34, 32, 32): "dark"}
HEADS = {
    "wooden_hammer": {"light": (201, 160, 99), "mid": (158, 117, 64), "dark": (92, 64, 34)},
    "iron_hammer": {"light": (255, 255, 255), "mid": (206, 206, 206), "dark": (98, 98, 98)},
}
# Head pixels only: everything right of the handle's top.
HEAD_MIN_X = 7

# Hand-drawn crack paths, (x, y) per pixel, for a 16x16 face.
TOP_CRACKS = {
    "cracked": [(8, 1), (8, 2), (7, 3), (7, 4), (7, 5), (8, 6)],
    "split": [(8, 1), (8, 2), (7, 3), (7, 4), (7, 5), (8, 6), (8, 7), (8, 8), (9, 9), (9, 10), (9, 11),
              (10, 12), (10, 13), (10, 14), (3, 9), (4, 9), (5, 10), (6, 10), (12, 4), (13, 5), (13, 6)],
}
SIDE_CRACKS = {
    "cracked": [(6, 0), (6, 1), (7, 2), (7, 3), (7, 4)],
    "split": [(6, 0), (6, 1), (7, 2), (7, 3), (7, 4), (8, 5), (8, 6), (8, 7), (9, 8), (9, 9),
              (12, 0), (12, 1), (13, 2), (13, 3)],
}


def vanilla(name):
    with zipfile.ZipFile(JAR) as jar:
        return Image.open(BytesIO(jar.read(f"assets/minecraft/textures/block/{name}.png"))).convert("RGBA").crop((0, 0, 16, 16))


def hammers():
    stone = Image.open(ASSETS / "textures/item/hammer.png").convert("RGBA")
    for name, tones in HEADS.items():
        out = stone.copy()
        px = out.load()
        for y in range(16):
            for x in range(HEAD_MIN_X, 16):
                r, g, b, a = px[x, y]
                tone = STONE.get((r, g, b))
                if a and tone:
                    px[x, y] = tones[tone] + (a,)
        out.save(ASSETS / f"textures/item/{name}.png")


def cracked(base, path):
    out = base.copy()
    px = out.load()
    for x, y in path:
        r, g, b, a = px[x, y]
        px[x, y] = (int(r * 0.25), int(g * 0.22), int(b * 0.2), 255)
        # A lighter lip beside the crack, where the wood has lifted.
        if x + 1 < 16:
            r, g, b, a = px[x + 1, y]
            px[x + 1, y] = (min(255, int(r * 1.12)), min(255, int(g * 1.12)), min(255, int(b * 1.1)), a)
    return out


def anvil():
    top = vanilla("stripped_oak_log_top")
    side = vanilla("oak_log")
    base_model = json.loads((ASSETS / "models/block/wooden_anvil.json").read_text(encoding="utf-8"))
    for stage in ("cracked", "split"):
        cracked(top, TOP_CRACKS[stage]).save(ASSETS / f"textures/block/wooden_anvil_top_{stage}.png")
        cracked(side, SIDE_CRACKS[stage]).save(ASSETS / f"textures/block/wooden_anvil_side_{stage}.png")
        model = {
            "parent": "hardwrought:block/wooden_anvil",
            "__comment": "Generated by tools/hammer_and_anvil_textures.py.",
            "textures": {
                "side": f"hardwrought:block/wooden_anvil_side_{stage}",
                "top": f"hardwrought:block/wooden_anvil_top_{stage}",
                "particle": base_model["textures"]["particle"],
            },
        }
        (ASSETS / f"models/block/wooden_anvil_{stage}.json").write_text(json.dumps(model, indent=2) + "\n", encoding="utf-8")

    rotations = {"north": 0, "east": 90, "south": 180, "west": 270}
    variants = {}
    for facing, y in rotations.items():
        for uses in range(24):
            model = "hardwrought:block/wooden_anvil"
            if uses >= 16:
                model += "_split"
            elif uses >= 8:
                model += "_cracked"
            variant = {"model": model}
            if y:
                variant["y"] = y
            variants[f"facing={facing},uses={uses}"] = variant
    (ASSETS / "blockstates/wooden_anvil.json").write_text(json.dumps({"variants": variants}, indent=2) + "\n",
                                                          encoding="utf-8")


if __name__ == "__main__":
    hammers()
    anvil()
    print("done")
